const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { test } = require('node:test');
const sharp = require('sharp');
const { S3 } = require('@aws-sdk/client-s3');
const { generateTokenList } = require('../dist/list');
const { generatePerpsList } = require('../dist/perpsList');
const { UploadManifest } = require('../dist/uploadManifest');

test('incremental asset generation preserves lists and retries failed uploads', async () => {
  const originalCwd = process.cwd();
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'token-uploads-'));
  const originalPut = S3.prototype.putObject;
  const originalResize = sharp.prototype.resize;
  let resizeCount = 0;
  sharp.prototype.resize = function (...args) {
    resizeCount++;
    return originalResize.apply(this, args);
  };
  const uploads = [];
  let fail = false;
  S3.prototype.putObject = async function (input) {
    if (fail) throw new Error('simulated R2 failure');
    uploads.push(input);
  };
  process.chdir(directory);
  try {
    const tokenDir = 'chains/evm/1/0xABC';
    await fs.mkdir(tokenDir, { recursive: true });
    const info = { address: '0xABC', name: 'Token', symbol: 'TOK', decimals: 18 };
    await fs.writeFile(`${tokenDir}/info.json`, JSON.stringify(info));
    const png = (color) => sharp({ create: { width: 128, height: 128, channels: 4, background: color } }).png().toBuffer();
    await fs.writeFile(`${tokenDir}/logo.png`, await png('red'));
    await fs.mkdir('perps/default/BTC', { recursive: true });
    await fs.writeFile('perps/default/BTC/logo.svg', '<svg/>');
    const run = async () => {
      await generateTokenList('chains/evm', 'tokenlist.json');
      await generatePerpsList('perps', 'perpslist.json');
    };
    await run();
    assert.deepEqual(uploads.map(x => x.Key), ['logos/1/0xabc.png', 'perps/default/BTC/logo.svg', 'perpslist.json']);
    assert.equal((await sharp(uploads[0].Body).metadata()).width, 64);
    assert.equal(resizeCount, 1);
    const originalTokens = JSON.parse(await fs.readFile('tokenlist.json')).tokens;
    uploads.length = 0;
    await run();
    assert.equal(uploads.length, 0);
    assert.equal(resizeCount, 1);
    assert.deepEqual(JSON.parse(await fs.readFile('tokenlist.json')).tokens, originalTokens);
    info.name = 'Renamed';
    await fs.writeFile(`${tokenDir}/info.json`, JSON.stringify(info));
    await run();
    assert.equal(uploads.length, 0);
    assert.equal(resizeCount, 1);
    assert.equal(JSON.parse(await fs.readFile('tokenlist.json')).tokens[0].name, 'Renamed');
    await fs.writeFile(`${tokenDir}/logo.png`, await png('blue'));
    await fs.writeFile('perps/default/BTC/logo.svg', '<svg>changed</svg>');
    await run();
    assert.deepEqual(uploads.map(x => x.Key), ['logos/1/0xabc.png', 'perps/default/BTC/logo.svg']);
    assert.equal(resizeCount, 2);
    uploads.length = 0;
    await fs.mkdir('perps/default/ETH');
    await fs.writeFile('perps/default/ETH/logo.jpg', Buffer.from('new logo'));
    await run();
    assert.deepEqual(uploads.map(x => x.Key), ['perps/default/ETH/logo.jpg', 'perpslist.json']);
    const manifestBeforeFailure = await fs.readFile('.upload-manifest.json', 'utf8');
    await fs.writeFile(`${tokenDir}/logo.png`, await png('green'));
    fail = true;
    await assert.rejects(run(), /Error processing/);
    assert.equal(await fs.readFile('.upload-manifest.json', 'utf8'), manifestBeforeFailure);
    fail = false;
    uploads.length = 0;
    await run();
    assert.deepEqual(uploads.map(x => x.Key), ['logos/1/0xabc.png']);
    await fs.writeFile('perps/default/BTC/logo.svg', '<svg>retry</svg>');
    fail = true;
    await assert.rejects(generatePerpsList('perps', 'perpslist.json'), /simulated R2 failure/);
    fail = false;
    uploads.length = 0;
    await run();
    assert.deepEqual(uploads.map(x => x.Key), ['perps/default/BTC/logo.svg']);
    uploads.length = 0;
    await fs.mkdir('chains/evm/1/0xDEF');
    await fs.writeFile('chains/evm/1/0xDEF/info.json', JSON.stringify({ ...info, address: '0xDEF' }));
    await fs.copyFile(`${tokenDir}/logo.png`, 'chains/evm/1/0xDEF/logo.png');
    await run();
    assert.deepEqual(uploads.map(x => x.Key), ['logos/1/0xdef.png']);
    uploads.length = 0;
    await fs.rm('perps/default/ETH', { recursive: true });
    await fs.rm('chains/evm/1/0xDEF', { recursive: true });
    await run();
    assert.deepEqual(uploads.map(x => x.Key), ['perpslist.json']);
    assert.equal(JSON.parse(await fs.readFile('tokenlist.json')).tokens.length, 1);
    assert.deepEqual(JSON.parse(await fs.readFile('perpslist.json'))[''], [['BTC', 'https://cdn.oku.trade/perps/default/BTC/logo.svg']]);
    const manifest = await UploadManifest.load();
    assert.equal(await manifest.upload('logos/1/0xabc.png', await fs.readFile(`${tokenDir}/logo.png`), 'new-recipe', async () => {}), true);
    await fs.writeFile('invalid.json', '[]');
    await assert.rejects(UploadManifest.load('invalid.json'), /Invalid upload manifest/);
  } finally {
    process.chdir(originalCwd);
    S3.prototype.putObject = originalPut;
    sharp.prototype.resize = originalResize;
    await fs.rm(directory, { recursive: true, force: true });
  }
});
